cc:
  name: "C++17"
  compile: "/usr/bin/g++ -O2 -pipe -static -s -std=gnu++17 -o ${name} ${src}"
  run: "./${name}"
py:
  py3:
    name: "Python 3"
    run: "/usr/bin/python3 ${src}"
  pypy3:
    name: "PyPy 3"
    run: "/usr/bin/pypy3 ${src}"
java:
  jdk17:
    name: "Java 17"
    compile: "/usr/bin/javac ${src}"
    run: "/usr/bin/java ${classname}"
